# Networks for communication between services
networks:
  caddy-mqtt:
    driver: bridge

# Volumes for data, config, and logs
volumes:
  config:
  data:
  log:
  caddy_data:
  caddy_config:
  portainer_data:
    driver: local

services:
  # mqtt5 Eclipse Mosquitto service with MQTT (1883) and WebSocket (1884)
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883"  # Default MQTT port
      - "1884:1884"  # WebSocket port for MQTT (WS)
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - caddy-mqtt

  # mqttx-web UI for the MQTT broker (this is the web interface)
  mqttx-web:
    image: emqx/mqttx-web
    container_name: mqttx-web
    restart: unless-stopped
    ports:
      - "5500:8080"  # Caddy container will route this internally
    networks:
      - caddy-mqtt
    command: "http-server -p 8080"  # Explicitly start http-server on port 8080

  # Portainer container for Docker management UI
  portainer:
    image: portainer/portainer-ce:2.21.4
    container_name: portainer
    restart: always
    ports:
      - "8000:8000" # Port for Edge Agent communication
      - "9443:9443" # Port for secure web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access to Docker engine
      - portainer_data:/data # Persistent data storage
    networks:
      - caddy-mqtt  

  # Caddy server for reverse proxying and HTTPS
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - WEB_DOMAIN=${WEB_DOMAIN}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - MQTT_PORT=${MQTT_PORT}
      - WEB_CONTAINER=${WEB_CONTAINER}
      - MQTT_CONTAINER=${MQTT_CONTAINER}
    ports:
      - "80:80"       # HTTP (will be redirected to HTTPS)
      - "443:443"     # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./public:/srv  # Mount the public directory here
    networks:
      - caddy-mqtt
