# Networks for communication between services
networks:
  caddy:
    driver: bridge

# Volumes for data, config, and logs
volumes:
  config:
  data:
  log:
  caddy_data:
  caddy_config:
    driver: local

services:
  # mqtt5 Eclipse Mosquitto service with MQTT (1883) and WebSocket (1884)
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883"  # Default MQTT port
      - "1884:1884"  # WebSocket port for MQTT (WS)
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - caddy

  # Caddy server for reverse proxying and HTTPS
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - WEB_DOMAIN=${WEB_DOMAIN}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - MQTT_PORT=${MQTT_PORT}
      - WEB_CONTAINER=${WEB_CONTAINER}
      - MQTT_CONTAINER=${MQTT_CONTAINER}
    ports:
      - "80:80"       # HTTP (will be redirected to HTTPS)
      - "443:443"     # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./public:/srv  # Mount the public directory here
    networks:
      - caddy
