# Networks for communication between services
networks:
  caddy:
    driver: bridge

# Volumes for data, config, and logs
volumes:
  config:
  data:
  log:
  caddy_data:
  caddy_config:
    driver: local

services:
  # MQTT5 Eclipse Mosquitto service with MQTT (1883) and WebSocket (1884)
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883"  # Default MQTT port
      - "1884:1884"  # WebSocket port for MQTT (WS)
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - caddy

  # Room Automation Scheduler Service
  scheduler:
    container_name: room_automation_scheduler
    build:
      context: ./Room_Automation_Scheduler
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env_scheduler
    ports:
      - "8000:8000"
    networks:
      - caddy

  # Caddy server for reverse proxying and HTTPS
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - WEB_DOMAIN=${WEB_DOMAIN}
    ports:
      - "80:80"       # HTTP (will be redirected to HTTPS)
      - "443:443"     # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./public:/srv  # Mount the public directory here
    networks:
      - caddy
    depends_on:
      - mqtt5
      - scheduler

  # Telegram Bot Service
  tg-bot:
    container_name: tg_bot_service
    build:
      context: ./room_automation_telegram_bot_main
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: 
      - .env_tg_bot
    networks:
      - caddy
    depends_on:
      - caddy
